_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
mode: simple
ignored_config_entities:
  - 'block.block.*'
  - key.key.ems_client_id
  - key.key.ems_client_secret
  - key.key.ems_token
  - 'system.menu.*'
  - system.site
