#!/bin/bash

set -eo pipefail

if [ -z "$TERMINUS_SITE" ] || [ -z "$TERMINUS_ENV" ]; then
  echo "TERMINUS_SITE and TERMINUS_ENV must be set." >&2
  exit 1
fi

exec terminus -n drush "${TERMINUS_SITE}.${TERMINUS_ENV}" -- "$@"
